Removing unnecessary lodash code
DEFRA/water-abstraction-import pull request #494
Opened 2022-11-28 16:24 UTC by Beckyrose200

https://github.com/DEFRA/water-abstraction-team/issues/25

Lodash is used a lot in our codebase. Although we are not totally removing this module, some of the functions in the code using lodash are unnecessary. Here we are removing the unnecessary ones are replacing it with vanilla js.

2023-01-17 08:20 UTC, Cruikshanks requested changes
TBH, these are more just to prove I honestly did read through this!

But definitely, we avoid leaving any commented-out code. And it's a personal preference that, even though you can, we don't embed functions inside functions (I think I spotted all the instances of this!)

2023-01-19 11:02 UTC, Beckyrose200 commented on src/modules/nald-import/services/load-csv-service.js
> +    arr.filter(item => args.every(arr => arr.includes(item)))
Ive moved this above the function now

2023-01-19 11:02 UTC, Beckyrose200 commented on src/modules/nald-import/lib/transform-returns-helpers.js
> +  }
I've moved this function out and above now

2023-01-19 11:03 UTC, Beckyrose200 commented on src/modules/nald-import/lib/repository.js
> +    }
I've moved this function outside of the class Repository as it was getting a typescript error when I moved it above

2023-01-19 11:03 UTC, Beckyrose200 commented on src/modules/licence-import/transform/mappers/agreement.js
> +    // const { agreement } = item
Opps, must have missed the commented out code. Its now removed <img src="https://media0.giphy.com/media/UkongEjInTYlOmV6FE/giphy.gif"/>

2023-01-19 13:17 UTC, Cruikshanks submitted a review, later dismissed

2023-01-19 16:21 UTC, merged