Replicate NALD returns when import triggered
DEFRA/water-abstraction-import pull request #822
Opened 2024-01-09 22:25 UTC by Cruikshanks

https://eaflood.atlassian.net/browse/WATER-4270

We've been working on building a better understanding of the jobs within the import service. We've even documented [details on the background jobs](https://github.com/DEFRA/water-abstraction-team/pull/39).

One of the things we'd like to be able to do is rebuild a DB locally from scratch. This will be especially useful for those new to the team when setting up their environment (and the rest of us when we break it!)

Something we noticed when trialling how to do this was that there was no return submission data. This would be useful to have and should be available in NALD for importing. Well, it turns out it is but it's hidden behind a hard-coded 'config' value (🤦🤡)

When we manually changed the value and ran the job our local DB was suddenly populated with lots of return information which makes testing much easier and the local experience more realistic.

Reviewing the commit history and the existing comment (`// Set to false as this is highly disruptive`) we understand this is not something you want to happen every time the job is run (which is at least once a day). But we can make a fair assumption it is something we do want to happen when we manually trigger the NALD import. Our only reason for doing so is when rebuilding the DB.

This change makes the necessary amendments to allow us to automatically replicate returns data when manually triggering the NALD import.

2024-01-09 23:40 UTC, Cruikshanks commented
SonarCloud is shouting at me about the lack of test coverage. But this has more to do with touching files that already have missing test coverage.

So, it's right. But based on this being legacy code and that we're just doing this to tweak manual triggers of the import I'd argue it's not worth the investment of time to make it happy.

Feel free to disagree though 🤷

2024-01-10 09:24 UTC, robertparkinson requested changes

2024-01-10 09:24 UTC, robertparkinson commented on config.js
> -      overwriteReturns: false, // Set to false as this is highly disruptive
I believe this is now never referenced so why not just remove it?

2024-01-10 09:39 UTC, robertparkinson commented on config.js
> -      overwriteReturns: false, // Set to false as this is highly disruptive
doh! morning brain. I thought this was you added the comment..

2024-01-10 09:39 UTC, robertparkinson approved these changes

2024-01-10 13:02 UTC, merged