Feature add import trigger for system
DEFRA/water-abstraction-import pull request #986
Opened 2024-08-06 11:24 UTC by jonathangoulding

2024-08-07 08:02 UTC, jonathangoulding commented
Complete logs for the added licence system queue and handler . 
```
 [08:00:00.033] INFO (1964): licence-import.queue-licences-system: started
| [08:00:10.110] INFO (1964): licence-import.queue-licences-system: finished
[08:00:20.053] INFO (1964): licence-import.import-licence-system: started
[08:00:20.053] INFO (1964): licence-import.import-licence-system: 6/33/03/*S/0033 sent to system import licence. Job number - 1
[08:00:40.049] INFO (1964): licence-import.queue-licences: started
[08:00:40.055] INFO (1964): licence-import.queue-licences - on complete started for 6/33/03/*S/0033
[08:00:40.057] INFO (1964): licence-import.queue-licences: finished
[08:00:50.058] INFO (1964): licence-import.import-licence: started
 numberOfJobs: 72300
[08:00:50.119] INFO (1964): licence-import.import-licence: finished
numberOfJobs: 72300

```

2024-08-07 09:29 UTC, Cruikshanks requested changes
Need to sort out the title and description before this is ready for review @jonathangoulding

2024-08-07 09:45 UTC, jonathangoulding commented
> Need to sort out the title and description before this is ready for review @jonathangoulding

Updated.

2024-08-07 11:37 UTC, Cruikshanks commented
Just recording it here.

The legacy code likes to log 'all the things'. That seems like the right call, but our experience is it actually just becomes noise when trying to dig into an issue. This is especially the case for high-volume things like import licences (80K of them).

Instead, we 'need' to have a log message when something goes wrong. We 'want' to have a message to say importing licences has started, and then when they have finished. We don't 'need' anything in between.

@jonathangoulding has come up with an improved version of how we handled this in [water-abstraction-service](https://github.com/DEFRA/water-abstraction-service) so is going to make those changes and then re-submit for review.

2024-08-07 13:48 UTC, jonathangoulding commented on src/modules/licence-import/jobs/queue-licences.js
> -    const numberOfJobs = licences.length
After discussion put this back.

2024-08-08 09:19 UTC, Cruikshanks approved these changes
<img src="https://media1.giphy.com/media/pULj9CGmIcfuzXTPfp/giphy.gif"/>

2024-08-08 13:03 UTC, merged